events {}

http {
    include /etc/nginx/mime.types;
    resolver 127.0.0.11 valid=30s;

    server {
        listen 443 ssl;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;
        root /var/www/html;
        
        # ---------------------------
        # STATIC FRONTEND
        # ---------------------------
        location / {
            root /var/www/static;
            index index.html;
        }
        # ---------------------------
        # API ROUTE (REAL-TIME STATUS)
        # ---------------------------
        location ~ ^/api/(.*)$ {
            set $monitor_backend monitor;
            proxy_pass http://$monitor_backend:5000/$1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        # ---------------------------
        # WORDPRESS (PHP-FPM)
        # ---------------------------
        location ^~ /wordpress {
            root /var/www/html;
            index index.php;

            try_files $uri $uri/ /wordpress/index.php?$args;

            location ~ \.php$ {
                resolver 127.0.0.11 valid=30s;
                set $wp wordpress:9000;
                include snippets/fastcgi-php.conf;
                fastcgi_pass $wp;
            }
        }
    }
}