events {}

http {
    include /etc/nginx/mime.types;
    
    server {
        listen 443 ssl;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;
        
        # ---------------------------
        # STATIC FRONTEND
        # ---------------------------
        location / {
            root /var/www/static;
            index index.html;
        }
        # ---------------------------
        # API ROUTE (REAL-TIME STATUS)
        # ---------------------------
        location /api/ {
            proxy_pass http://monitor:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        # root /var/www/html;
        # index index.php index.html;
        # server_name _;

        # location / {
        #     try_files $uri $uri/ =404;
        # }
        # ---------------------------
        # WORDPRESS (PHP-FPM)
        # ---------------------------
        location /wordpress/ {
            root /var/www/html;
            index index.php;

            try_files $uri $uri/ /wordpress/index.php?$args;
        }
        location ~ \.php$ {
            include snippets/fastcgi-php.conf;
            fastcgi_pass wordpress:9000;
        }
    }
}